// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQncvT9XQW3GjXRJN92VZHYNoLzZ2ugeU',
    appId: '1:799896518184:web:395ff55661b1e586d9ff1d',
    messagingSenderId: '799896518184',
    projectId: 'vms-green',
    authDomain: 'vms-green.firebaseapp.com',
    storageBucket: 'vms-green.firebasestorage.app',
    measurementId: 'G-QCNJQ5VDDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgWZcRseJD23-ndtI8GRphurrwQVKGrAM',
    appId: '1:799896518184:android:7201ae9031fcdcb4d9ff1d',
    messagingSenderId: '799896518184',
    projectId: 'vms-green',
    storageBucket: 'vms-green.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKwpS1DNIQCUfgR4LWBRgYtuV5rfMvDHY',
    appId: '1:799896518184:ios:0ee4c7457f7107f0d9ff1d',
    messagingSenderId: '799896518184',
    projectId: 'vms-green',
    storageBucket: 'vms-green.firebasestorage.app',
    iosBundleId: 'com.greencrescent.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKwpS1DNIQCUfgR4LWBRgYtuV5rfMvDHY',
    appId: '1:799896518184:ios:0ee4c7457f7107f0d9ff1d',
    messagingSenderId: '799896518184',
    projectId: 'vms-green',
    storageBucket: 'vms-green.firebasestorage.app',
    iosBundleId: 'com.greencrescent.flutterApp',
  );
}
