import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI
import 'core/theme/app_theme.dart';
import 'core/theme/theme_provider.dart';
import 'core/constants/app_constants.dart';
import 'core/services/localization_service.dart';
import 'core/services/push_notification_service.dart';
import 'features/auth/screens/splash_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Initialize Firebase with generated options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  debugPrint('✅ Firebase initialized');

  // Initialize Push Notifications & get FCM token
  await PushNotificationService().initialize();

  // Initialize Supabase
  await Supabase.initialize(
    url: AppConstants.supabaseUrl,
    anonKey: AppConstants.supabaseAnonKey,
  );
  debugPrint('✅ Supabase initialized');

  runApp(const VMSApp());
}

class VMSApp extends StatefulWidget {
  const VMSApp({super.key});

  static _VMSAppState? of(BuildContext context) =>
      context.findAncestorStateOfType<_VMSAppState>();

  @override
  State<VMSApp> createState() => _VMSAppState();
}

class _VMSAppState extends State<VMSApp> {
  final ThemeProvider _themeProvider = ThemeProvider();
  final LocalizationService _localizationService = LocalizationService();

  @override
  void initState() {
    super.initState();
    _themeProvider.addListener(_onThemeChanged);
    _localizationService.addListener(_onLocaleChanged);
  }

  @override
  void dispose() {
    _themeProvider.removeListener(_onThemeChanged);
    _localizationService.removeListener(_onLocaleChanged);
    super.dispose();
  }

  void _onThemeChanged() {
    setState(() {});
    _updateSystemUI();
  }

  void _onLocaleChanged() => setState(() {});

  void _updateSystemUI() {
    final isDark = _themeProvider.isDarkMode;
    SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: isDark ? Brightness.light : Brightness.dark,
      systemNavigationBarColor: isDark ? const Color(0xFF1E1E1E) : Colors.white,
      systemNavigationBarIconBrightness: isDark ? Brightness.light : Brightness.dark,
    ));
  }

  void setThemeMode(ThemeMode mode) => _themeProvider.setThemeMode(mode);
  ThemeMode get themeMode => _themeProvider.themeMode;
  bool get isDarkMode => _themeProvider.isDarkMode;

  void setLocale(Locale locale) => _localizationService.setLocale(locale);
  Locale get locale => _localizationService.locale;
  bool get isArabic => _localizationService.isArabic;
  void setEnglish() => _localizationService.setEnglish();
  void setArabic() => _localizationService.setArabic();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'VMS Green Crescent',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: _themeProvider.themeMode,
      locale: _localizationService.locale,
      supportedLocales: LocalizationService.supportedLocales,
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      builder: (context, child) {
        return Directionality(
          textDirection: _localizationService.isArabic ? TextDirection.rtl : TextDirection.ltr,
          child: child!,
        );
      },
      home: const SplashScreen(),
    );
  }
}